### ISSUE TITLE
Craft 2.5+ compatibility?

### ISSUE THREAD

**Issue by jacobgraf** [creativeorange/Craft-redactor-font-awesome#2]
This plugin doesn't seem to work in the Craft 2.5 Beta. Any plans to update it?

The plugin loads and you can select icons, etc, but there is a js error thrown in the console which breaks all the other js on the page (e.g. deleting rows from a Matrix field, etc)

`Uncaught TypeError: this.button.setAwesome is not a function`

**Comment by brainpink** [comment]
Thanks for the heads up, we'll look into it

**Comment by brainpink** [comment]
@jacobgraf We have updated the plugin
